### PR TITLE
Add serialization/deserialization

### PR DESCRIPTION
**Pull request by seppo0010**

### CODE REVIEW

**Comment by kjgorman** [comment]
Looks pretty legit. It's kind of weird we need to wrap them in `io::Result` when it's all happening just with `Vec<u8>`; is that just a result of using `byteorder`?

Also, could you maybe add a failure case test for `from_vec` receiving a vec that doesn't match the expected packing?

**Comment by seppo0010** [comment]
@kjgorman I can't imagine any case where it would fail, expect if the length is less than 21. Is there any sanity check I can apply to `self.M`?

**Comment by kjgorman** [comment]
That 's cool then.

Thanks for the contributions, I'll push `0.3.0` up to crates with this (and your other changes) merged in.

**Comment by kjgorman** [comment]
And sorry it took so long to get to this!

**Pull request merged**
